// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CheckBox: typeof import('./src/components/DCheckBox.vue')['default']
    ContentEditable: typeof import('./src/components/ContentEditable.vue')['default']
    DCheckBox: typeof import('./src/components/DCheckBox.vue')['default']
    DDrawer: typeof import('./src/components/DDrawer.vue')['default']
    DDropDown: typeof import('./src/components/DDropDown.vue')['default']
    DLottie: typeof import('./src/components/DLottie.vue')['default']
    DSelect: typeof import('./src/components/DSelect.vue')['default']
    ElbetTicket: typeof import('./src/components/ElbetTicket.vue')['default']
    EmojiCard: typeof import('./src/components/EmojiCard.vue')['default']
    EmptyTodo: typeof import('./src/components/EmptyTodo.vue')['default']
    GhostInput: typeof import('./src/components/GhostInput.vue')['default']
    LayoutBlur: typeof import('./src/components/LayoutBlur.vue')['default']
    LeftPanel: typeof import('./src/components/LeftPanel.vue')['default']
    Lottie: typeof import('./src/components/Lottie.vue')['default']
    NotFound: typeof import('./src/pages/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubtleBg: typeof import('./src/components/SubtleBg.vue')['default']
    TextArea: typeof import('./src/components/ContentEditable.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    TodoDrawer: typeof import('./src/components/TodoDrawer.vue')['default']
    TodoInput: typeof import('./src/components/TodoInput.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
  }
}
