// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CheckBox: typeof import('./src/components/DCheckBox.vue')['default']
    DCheckBox: typeof import('./src/components/DCheckBox.vue')['default']
    GhostInput: typeof import('./src/components/GhostInput.vue')['default']
    LayoutBlur: typeof import('./src/components/LayoutBlur.vue')['default']
    LeftPanel: typeof import('./src/components/LeftPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoInput: typeof import('./src/components/TodoInput.vue')['default']
  }
}
